DROP TABLE users;
CREATE TABLE users (id VARCHAR2(100) NOT NULL, name VARCHAR2(100) NOT NULL, password VARCHAR2(100) NOT NULL, level NUMBER NOT NULL, login NUMBER NOT NULL, recommend NUMBER NOT NULL);
ALTER TABLE users ADD PRIMARY KEY (id);